Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: main
      CodeUri: E:\Projects\aws-profile-go
      Runtime: go1.x
      Architectures:
        - x86_64