openapi: 3.0.3
info:
  title: Go profile API
  version: 0.0.1

servers:
  - url: https://q37jrwzos8.execute-api.eu-west-1.amazonaws.com/dev/

paths:
  /image:
    get:
      security:
        - basic: []
      tags:
        - image
      summary: Returns a URL to upload image to
      description:
        Pass the "image" query param with the name of the image you will upload.
        It will return two URLs. One is used to upload the image using PUT request,
        and the second one is to use to access the image from the browser.
      parameters:
        - in: query
          name: image
          required: true
          schema:
            type: string
            example: Hello%20World.png
      responses:
        "200":
          description: Signed URL created
          content:
            application/json:
              schema:
                type: object
                properties:
                  uploadUrl:
                    type: string
                    example: http://aws.com/ima
                    description: Destination path which is used to upload the image to
                  url:
                    type: string
                    description: URL by which the uploaded image then can be accessed to download
        "401":
          $ref: "#/components/responses/Unauthorized"

  /profile:
    get:
      tags:
        - profile
      summary: Returns profile info
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "./validation-schemas/save-profile.validation.json"

    post:
      security:
        - basic: []
      tags:
        - profile
      summary: Saves profile info
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./validation-schemas/save-profile.validation.json"
      responses:
        "201":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ItemCreated"
        "401":
          $ref: "#/components/responses/Unauthorized"

  /skills:
    get:
      tags:
        - get-skills
      summary: Returns get-skills
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "./validation-schemas/save-skills.validation.json"
    post:
      security:
        - basic: []
      tags:
        - get-skills
      summary: Saves get-skills
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./validation-schemas/save-skills.validation.json"
      responses:
        "201":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ItemCreated"
        "401":
          $ref: "#/components/responses/Unauthorized"

  /languages:
    get:
      tags:
        - languages
      summary: Returns languages
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  example: "English B2+"
                  minLength: 2
    post:
      security:
        - basic: []
      tags:
        - languages
      summary: Saves languages
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: string
                example: "English B2+"
                minLength: 2
      responses:
        "201":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ItemCreated"
        "401":
          $ref: "#/components/responses/Unauthorized"

  /educations:
    get:
      tags:
        - educations
      summary: Returns education
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  example: "Master degree"
                  minLength: 2
    post:
      security:
        - basic: []
      tags:
        - educations
      summary: Saves education
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: string
                example: "Master degree"
                minLength: 2
      responses:
        "201":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ItemCreated"
        "401":
          $ref: "#/components/responses/Unauthorized"

  /projects:
    get:
      tags:
        - projects
      summary: Returns projects
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "./validation-schemas/save-projects.validation.json"
    post:
      security:
        - basic: []
      tags:
        - projects
      summary: Saves projects
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./validation-schemas/save-projects.validation.json"
      responses:
        "201":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ItemCreated"
        "401":
          $ref: "#/components/responses/Unauthorized"

components:
  schemas:
    ItemCreated:
      type: object
      properties:
        message:
          type: string
          example: Created

    AuthError:
      type: object
      properties:
        message:
          type: string
      required:
        - code
        - message

  responses:
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/AuthError"

  securitySchemes:
    basic:
      type: http
      scheme: basic
